<a href="https://colab.research.google.com/github/ZeshanGIT/Style/blob/master/GeneratePath.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import random
import numpy

In [0]:
x = int(input("X: ") or 10)
y = int(input("Y: ") or 10)
noo = int(input("Number of obstacles: ") or 10)
nop = int(input("Number of paths: ") or 10)
mapXY = numpy.zeros(x*y,dtype=int)
for i in range(noo):
  mapXY[i] = 1

while mapXY[0]==1 or mapXY[x*y-1]==1:
  random.shuffle(mapXY)
mapXY = mapXY.reshape((x,y))
print(mapXY)
mapXY = [numpy.ones(x,dtype=int)] + [mapXY] + [numpy.ones(x,dtype=int)]


# mapXY.insert()
# mapXY = numpy.array(mapXY).ravel()
# mapXY = mapXY.reshape((x+2,y+2))
print(mapXY)
for i in range(y):
  mapXY[i] = mapXY[i].insert(0,1)
print(mapXY)

X: 
Y: 
Number of obstacles: 
Number of paths: 
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]]
[array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0]]), array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])]


AttributeError: ignored

In [0]:
paths = []

In [0]:
for i in range(nop):
  path = [[0,0]]
  node = [0,0]
  tempnode = f(node)
  while mapXY[tempnode[0],tempnode[1]] == 1:
    tempnode = f(node)
    if :
    path.append(node)
    
  print(node)
  print(path)
  paths.append(path)

[1 0]
[[0, 0]]
[0 1]
[[0, 0]]
[1 0]
[[0, 0]]
[0 1]
[[0, 0]]
[1 1]
[[0, 0]]
[1 0]
[[0, 0]]
[1 1]
[[0, 0]]
[1 0]
[[0, 0]]
[1 0]
[[0, 0]]
[1 1]
[[0, 0]]


In [0]:
def f(p): 
  return {
      '0': numpy.add(p,[0,1]),
      '1': numpy.add(p,[1,0]),
      '2': numpy.add(p,[1,1])
  }[str(random.randint(0,2))]

In [0]:
class node:
#   x = y = 0
  def __init__(self,x,y):
    self.x = x
    self.y = y
    self.nextNode = list()
    if(x != X or y != Y):
      print("X: ", x, "\nY: ", y)
      cond = x<X and mapXY[x+1][y] != 1
      print("Cond1 : \n", "\tx : ", x, "\tx : ", y, "\tCond  : ",  cond)
      if(cond):
        self.nextNode.append(node(x+1,y))
      cond  = x<X and y<Y and mapXY[x+1][y+1] != 1 
      print("Cond2 : \n", "\tx : ", x, "\tx : ", y, "\tCond  : ",  cond)
      if(cond):
        self.nextNode.append(node(x+1,y+1))
      cond = y<Y and mapXY[x][y+1] != 1
      print("Cond3 : \n", "\tx : ", x, "\tx : ", y, "\tCond  : ",  cond)
      if(cond):
        self.nextNode.append(node(x,y+1))
      print(self.nextNode)
    else:
      print("Last Node !")
      self.nextNode = 0
  
  def __str__(self):
    return str(self.x) + "\t" + str(self.y) + "\n"
  #+ "lastNode" if self.nextNode == 0 else [str(x) for x in self.nextNode]
    

In [0]:
n = 0
n = node(0,0)

X:  0 
Y:  0
Cond1 : 
 	x :  0 	x :  0 	Cond  :  True
X:  1 
Y:  0
Cond1 : 
 	x :  1 	x :  0 	Cond  :  True
X:  2 
Y:  0
Cond1 : 
 	x :  2 	x :  0 	Cond  :  False
Cond2 : 
 	x :  2 	x :  0 	Cond  :  False
Cond3 : 
 	x :  2 	x :  0 	Cond  :  True
X:  2 
Y:  1
Cond1 : 
 	x :  2 	x :  1 	Cond  :  False
Cond2 : 
 	x :  2 	x :  1 	Cond  :  False
Cond3 : 
 	x :  2 	x :  1 	Cond  :  True
Last Node !
Cond2 : 
 	x :  1 	x :  0 	Cond  :  True
X:  2 
Y:  1
Cond1 : 
 	x :  2 	x :  1 	Cond  :  False
Cond2 : 
 	x :  2 	x :  1 	Cond  :  False
Cond3 : 
 	x :  2 	x :  1 	Cond  :  True
Last Node !
Cond3 : 
 	x :  1 	x :  0 	Cond  :  True
X:  1 
Y:  1
Cond1 : 
 	x :  1 	x :  1 	Cond  :  True
X:  2 
Y:  1
Cond1 : 
 	x :  2 	x :  1 	Cond  :  False
Cond2 : 
 	x :  2 	x :  1 	Cond  :  False
Cond3 : 
 	x :  2 	x :  1 	Cond  :  True
Last Node !
Cond2 : 
 	x :  1 	x :  1 	Cond  :  True
Last Node !
Cond3 : 
 	x :  1 	x :  1 	Cond  :  True
X:  1 
Y:  2
Cond1 : 
 	x :  1 	x :  2 	Cond  :  True
Last Node !
Cond2 : 

In [0]:
X = 2
Y = 2
mapXY = [[0,0,0],[0,0,0],[0,0,0]]
print(mapXY,X,Y)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]] 2 2


In [0]:
paths = list()
paths.append([n])
print(paths)
for i in range(len(n.nextNode)-1):
  paths.append(paths[0])

[[<__main__.node object at 0x7f9ceef410b8>]]


In [0]:
print([i for i in paths])

[[<__main__.node object at 0x7f9ceef410b8>], [<__main__.node object at 0x7f9ceef410b8>], [<__main__.node object at 0x7f9ceef410b8>]]
